instruments = {
    "GENERAL_MIDI": (
        "Grand Piano", "Bright Piano", "El. Grd Piano", "Honky-tonk Piano",
        "El. Piano 1", "El. Piano 2", "Harpsichord", "Clavi",
        "Celesta", "Glockenspiel", "Music Box", "Vibraphone",
        "Marimba", "Xylophone", "Tubular Bells", "Santur",
        "Drawbar Organ", "Percussive Organ", "Rock Organ", "Church Organ",
        "Reed Organ", "Accordion (french)", "Harmonica", "Tango Accordion",
        "Ac. Guitar (nylon)", "Ac. Guitar (steel)", "El. Guitar (jazz)", "El. Guitar (clean)",
        "El. Guitar (muted)", "Overdriven Guitar", "Distortion Guitar", "Guitar harmonics",
        "Acoustic Bass", "Finger Bass", "Picked Bass", "Fretless Bass",
        "Slap Bass 1", "Slap Bass 2", "Synth Bass 1", "Synth Bass 2",
        "Violin", "Viola", "Cello", "Contrabass",
        "Tremolo Strings", "Pizzicato Strings", "Orchestral Harp", "Timpani",
        "String Ensemble 1", "String Ensemble 2", "Synth Strings 1", "Synth Strings 2",
        "Choir Aahs", "Voice Oohs", "Synth Voice", "Orchestra Hit",
        "Trumpet", "Trombone", "Tuba", "Muted Trumpet",
        "French Horn", "Brass Section", "Synth Brass 1", "Synth Brass 2",
        "Soprano Sax", "Alto Sax", "Tenor Sax", "Baritone Sax",
        "Oboe", "English Horn", "Bassoon", "Clarinet",
        "Piccolo", "Flute", "Recorder", "Pan Flute",
        "Blown Bottle", "Shakuhachi", "Whistle", "Ocarina",
        "Lead 1 (square)", "Lead 2 (sawtooth)", "Lead 3 (calliope)", "Lead 4 (chiff)",
        "Lead 5 (charang)", "Lead 6 (voice)", "Lead 7 (fifths)", "Lead 8 (bass+lead)",
        "Pad 1 (fantasia)", "Pad 2 (warm)", "Pad 3 (polysynth)", "Pad 4 (choir)",
        "Pad 5 (bowed)", "Pad 6 (metallic)", "Pad 7 (halo)", "Pad 8 (sweep)",
        "FX 1 (rain)", "FX 2 (soundtrack)", "FX 3 (crystal)", "FX 4 (atmosphere)",
        "FX 5 (brightness)", "FX 6 (goblins)", "FX 7 (echoes)", "FX 8 (sci-fi)",
        "Sitar", "Banjo", "Shamisen", "Koto",
        "Kalimba", "Bag pipe", "Fiddle", "Shanai",
        "Tinkle Bell", "Agogo", "Steel Drums", "Woodblock",
        "Taiko Drum", "Melodic Tom", "Synth Drum", "Reverse Cymbal",
        "Gt. Fret Noise", "Breath Noise", "Seashore", "Bird Tweet",
        "Teleph. Ring", "Helicopter", "Applause", "Gunshot"
    ),
    "MT32": (
        "Piano 1", "Piano 2", "Piano 3", "Detuned EP 1",
        "E.Piano1", "E.Piano2", "Detuned EP2", "Honky-Tonk",
        "Organ 1", "Organ 2", "Organ 3", "Detuned Or. 1",
        "Church Org. 2", "Church Org.", "Church Org.", "Accordion Fr.",
        "Harpsichord", "Coupled Hps.", "Coupled Hps.", "Clav.",
        "Clav.", "Clav.", "Celesta", "Celesta",
        "Synth Brass1", "Synth Brass2", "Synth Brass3", "Synth Brass4",
        "Synth Bass1", "Synth Bass2", "Synth Bass3", "Synth Bass4",
        "Fantasia", "Syn Calliope", "Choir Aahs", "Bowed Glass",
        "Soundtrack", "Atmosphere", "Crystal", "Bag Pipe",
        "Tinkle Bell", "Ice Rain", "Oboe", "Pan Flute",
        "Saw Wave", "Charang", "Tubular Bells", "Square Wave",
        "Strings", "Tremolo Str.", "Slow Strings", "Pizzicato Str.",
        "Violin", "Viola", "Cello", "Cello",
        "Contrabass", "Harp", "Harp", "Nylon-str. Gt",
        "Steel-Str. Gt", "Chorus Gt.", "Funk Gt.", "Sitar",
        "Acoustic Bs.", "Fingered Bs.", "Picked Bs.", "Fretless Bs.",
        "Slap Bs. 1", "Slap Bs. 2", "Fretless Bs.", "Fretless Bs.",
        "Flute", "Flute", "Piccolo", "Piccolo",
        "Recorder", "Pan Flute", "Soprano Sax", "Alto Sax",
        "Tenor Sax", "Baritone Sax", "Clarinet", "Clarinet",
        "Oboe", "English Horn", "Bassoon", "Harmonica",
        "Trumped", "Muted Trumpet", "Trombone", "Trombone",
        "French Horn", "French Horn", "Tuba", "Brass",
        "Brass 2", "Vibraphone", "Vibraphone", "Kalimba",
        "Tinkle Bell", "Glockenspiel", "Tubular-Bell", "Xylophone",
        "Marimba", "Koto", "Taisho Koto", "Shakuhachi",
        "Whistle", "Whistle", "Bottle Blow", "Pan Flute",
        "Timpani", "Melo Tom", "Melo Tom", "Synth Drum",
        "Synth Drum", "Taiko", "Taiko", "Reverse Cym.",
        "Castanets", "Tinkle Bell", "Orchestra Hit", "Telephone",
        "Bird", "Helicopter", "Bowed Glass", "Ice Rain"
    ),
    "DRUM_SETS": {
        "STANDARD_SET": {
            27: "Closed Hi Hat [EXC1]", 28: "Pedal Hi-Hat [EXC1]", 29: "Open Hi Hat [EXC1]", 30: "Ride Cymbal",
            35: "Kick drum2", 36: "Kick drum1", 37: "Side Stick", 38: "Snare Drum 1", 39: "Hand Clap",
            40: "Snare Drum 2", 41: "Low Floor Tom", 42: "Closed Hi Hat [EXC1]", 43: "High Floor Tom",
            44: "Pedal Hi-Hat [EXC1]", 45: "Low Tom", 46: "Open Hi-Hat [EXC1]", 47: "Low-Mid Tom",
            48: "Hi Mid Tom", 49: "Crash Cymbal 1", 50: "High Tom", 51: "Ride Cymbal 1", 52: "Chinese Cymbal",
            53: "Ride Bell", 54: "Tambourine", 55: "Splash Cymbal", 56: "Cowbell", 57: "Crash Cymbal 2",
            58: "Vibraslap", 59: "Ride Cymbal 2", 60: "Hi Bongo", 61: "Low Bongo", 62: "Mute Hi Conga",
            63: "Open Hi Conga", 64: "Low Conga", 65: "High Timbale", 66: "Low Timbale", 67: "High Agogo",
            68: "Low Agogo", 69: "Cabasa", 70: "Maracas", 71: "Short Whistle[EXC2]", 72: "Long Whistle[EXC2]",
            73: "Short Guiro [EXC3]", 74: "Long Guiro [EXC3]", 75: "Claves", 76: "Hi Wood Block",
            77: "Low Wood Block", 78: "Mute Cuica [EXC4]", 79: "Open Cuica [EXC4]", 80: "Mute Triangle [EXC5]",
            81: "Open Triangle[EXC5]", 82: "Applauses", 88: "Applauses", 94: "Helicopter", 96: "Gun Shot",
            102: "Birds", 106: "SeaShore"
        },
        "POWER_SET": {
            35: "Jazz BD 2", 36: "Jazz BD 1", 38: "Gated Snare", 39: "Hand Clap", 40: "Elec Snare Drum"
        },
        "BRUSH": {
            35: "Kick drum", 36: "Kick drum", 37: "Rim Shot", 38: "Brush Tap", 39: "Brush Slap", 40: "Brush Swirl"
        },
        "ORCHESTRA": {
            35: "Kick drum", 36: "Kick drum", 38: "Snare Drum 2", 39: "Castanets", 40: "Snare Drum 2",
            41: "Timpani F", 42: "Timpani F#", 43: "Timpani G", 44: "Timpani G#", 45: "Timpani A",
            46: "Timpani A#", 47: "Timpani B", 48: "Timpani c", 49: "Timpani c#", 50: "Timpani d",
            51: "Timpani d#", 52: "Timpani e", 53: "Timpani f", 54: "Tambourine", 56: "Cowbell", 73: "Vibra Slap",
            75: "Claves"
        },
        "CM_64_32": {
            27: "Closed Hi Hat [EXC1]", 28: "Pedal Hi-Hat [EXC1]", 29: "Open Hi Hat [EXC1]", 30: "Ride Cymbal",
            35: "Kick drum", 36: "Kick drum", 37: "Rim Shot", 38: "Snare Drum", 39: "Hand Clap",
            40: "Elec Snare Drum", 41: "Acoustic Low Tom", 42: "Closed Hi-Hat [Exc1]", 43: "Acoustic Low Tom",
            44: "Open Hi-Hat 2", 45: "Acoustic Middle Tom", 46: "Open Hi-Hat 1 [Exc1]", 47: "Acoustic Middle Tom",
            48: "Acoustic High Tom", 49: "Crash Cymbal", 50: "Acoustic High Tom", 51: "Ride Cymbal",
            54: "Tambourine", 56: "Cowbell", 75: "Claves"
        }
    }
}